function Select() {
  const countries = [
    { id: "af", value: "Afghanistan", flag: "🇦🇫" },
    { id: "al", value: "Albania", flag: "🇦🇱" },
    { id: "dz", value: "Algeria", flag: "🇩🇿" },
    { id: "ad", value: "Andorra", flag: "🇦🇩" },
    { id: "ao", value: "Angola", flag: "🇦🇴" },
    { id: "ag", value: "Antigua and Barbuda", flag: "🇦🇬" },
    { id: "ar", value: "Argentina", flag: "🇦🇷" },
    { id: "am", value: "Armenia", flag: "🇦🇲" },
    { id: "au", value: "Australia", flag: "🇦🇺" },
    { id: "at", value: "Austria", flag: "🇦🇹" },
    { id: "az", value: "Azerbaijan", flag: "🇦🇿" },
    { id: "bs", value: "Bahamas", flag: "🇧🇸" },
    { id: "bh", value: "Bahrain", flag: "🇧🇭" },
    { id: "bd", value: "Bangladesh", flag: "🇧🇩" },
    { id: "bb", value: "Barbados", flag: "🇧🇧" },
    { id: "by", value: "Belarus", flag: "🇧🇾" },
    { id: "be", value: "Belgium", flag: "🇧🇪" },
    { id: "bz", value: "Belize", flag: "🇧🇿" },
    { id: "bj", value: "Benin", flag: "🇧🇯" },
    { id: "bt", value: "Bhutan", flag: "🇧🇹" },
    { id: "bo", value: "Bolivia", flag: "🇧🇴" },
    { id: "ba", value: "Bosnia and Herzegovina", flag: "🇧🇦" },
    { id: "bw", value: "Botswana", flag: "🇧🇼" },
    { id: "br", value: "Brazil", flag: "🇧🇷" },
    { id: "bn", value: "Brunei", flag: "🇧🇳" },
    { id: "bg", value: "Bulgaria", flag: "🇧🇬" },
    { id: "bf", value: "Burkina Faso", flag: "🇧🇫" },
    { id: "bi", value: "Burundi", flag: "🇧🇮" },
    { id: "kh", value: "Cambodia", flag: "🇰🇭" },
    { id: "cm", value: "Cameroon", flag: "🇨🇲" },
    { id: "ca", value: "Canada", flag: "🇨🇦" },
    { id: "cv", value: "Cape Verde", flag: "🇨🇻" },
    { id: "cf", value: "Central African Republic", flag: "🇨🇫" },
    { id: "td", value: "Chad", flag: "🇹🇩" },
    { id: "cl", value: "Chile", flag: "🇨🇱" },
    { id: "cn", value: "China", flag: "🇨🇳" },
    { id: "co", value: "Colombia", flag: "🇨🇴" },
    { id: "km", value: "Comoros", flag: "🇰🇲" },
    { id: "cr", value: "Costa Rica", flag: "🇨🇷" },
    { id: "hr", value: "Croatia", flag: "🇭🇷" },
    { id: "cu", value: "Cuba", flag: "🇨🇺" },
    { id: "cy", value: "Cyprus", flag: "🇨🇾" },
    { id: "cz", value: "Czech Republic", flag: "🇨🇿" },
    { id: "cd", value: "Democratic Republic of the Congo", flag: "🇨🇩" },
    { id: "dk", value: "Denmark", flag: "🇩🇰" },
    { id: "dj", value: "Djibouti", flag: "🇩🇯" },
    { id: "dm", value: "Dominica", flag: "🇩🇲" },
    { id: "do", value: "Dominican Republic", flag: "🇩🇴" },
    { id: "ec", value: "Ecuador", flag: "🇪🇨" },
    { id: "eg", value: "Egypt", flag: "🇪🇬" },
    { id: "sv", value: "El Salvador", flag: "🇸🇻" },
    { id: "gq", value: "Equatorial Guinea", flag: "🇬🇶" },
    { id: "er", value: "Eritrea", flag: "🇪🇷" },
    { id: "ee", value: "Estonia", flag: "🇪🇪" },
    { id: "sz", value: "Eswatini", flag: "🇸🇿" },
    { id: "et", value: "Ethiopia", flag: "🇪🇹" },
    { id: "fj", value: "Fiji", flag: "🇫🇯" },
    { id: "fi", value: "Finland", flag: "🇫🇮" },
    { id: "fr", value: "France", flag: "🇫🇷" },
    { id: "gf", value: "French Guiana", flag: "🇬🇫" },
    { id: "ga", value: "Gabon", flag: "🇬🇦" },
    { id: "gm", value: "Gambia", flag: "🇬🇲" },
    { id: "ge", value: "Georgia", flag: "🇬🇪" },
    { id: "de", value: "Germany", flag: "🇩🇪" },
    { id: "gh", value: "Ghana", flag: "🇬🇭" },
    { id: "gr", value: "Greece", flag: "🇬🇷" },
    { id: "gd", value: "Grenada", flag: "🇬🇩" },
    { id: "gt", value: "Guatemala", flag: "🇬🇹" },
    { id: "gn", value: "Guinea", flag: "🇬🇳" },
    { id: "gw", value: "Guinea-Bissau", flag: "🇬🇼" },
    { id: "gy", value: "Guyana", flag: "🇬🇾" },
    { id: "ht", value: "Haiti", flag: "🇭🇹" },
    { id: "hn", value: "Honduras", flag: "🇭🇳" },
    { id: "hk", value: "Hong Kong", flag: "🇭🇰" },
    { id: "hu", value: "Hungary", flag: "🇭🇺" },
    { id: "is", value: "Iceland", flag: "🇮🇸" },
    { id: "in", value: "India", flag: "🇮🇳" },
    { id: "id", value: "Indonesia", flag: "🇮🇩" },
    { id: "ir", value: "Iran", flag: "🇮🇷" },
    { id: "iq", value: "Iraq", flag: "🇮🇶" },
    { id: "ie", value: "Ireland", flag: "🇮🇪" },
    { id: "il", value: "Israel", flag: "🇮🇱" },
    { id: "it", value: "Italy", flag: "🇮🇹" },
    { id: "ci", value: "Ivory Coast", flag: "🇨🇮" },
    { id: "jm", value: "Jamaica", flag: "🇯🇲" },
    { id: "jp", value: "Japan", flag: "🇯🇵" },
    { id: "jo", value: "Jordan", flag: "🇯🇴" },
    { id: "kz", value: "Kazakhstan", flag: "🇰🇿" },
    { id: "ke", value: "Kenya", flag: "🇰🇪" },
    { id: "ki", value: "Kiribati", flag: "🇰🇮" },
    { id: "xk", value: "Kosovo", flag: "🇽🇰" },
    { id: "kw", value: "Kuwait", flag: "🇰🇼" },
    { id: "kg", value: "Kyrgyzstan", flag: "🇰🇬" },
    { id: "la", value: "Laos", flag: "🇱🇦" },
    { id: "lv", value: "Latvia", flag: "🇱🇻" },
    { id: "lb", value: "Lebanon", flag: "🇱🇧" },
    { id: "ls", value: "Lesotho", flag: "🇱🇸" },
    { id: "lr", value: "Liberia", flag: "🇱🇷" },
    { id: "ly", value: "Libya", flag: "🇱🇾" },
    { id: "li", value: "Liechtenstein", flag: "🇱🇮" },
    { id: "lt", value: "Lithuania", flag: "🇱🇹" },
    { id: "lu", value: "Luxembourg", flag: "🇱🇺" },
    { id: "mo", value: "Macau", flag: "🇲🇴" },
    { id: "mg", value: "Madagascar", flag: "🇲🇬" },
    { id: "mw", value: "Malawi", flag: "🇲🇼" },
    { id: "my", value: "Malaysia", flag: "🇲🇾" },
    { id: "mv", value: "Maldives", flag: "🇲🇻" },
    { id: "ml", value: "Mali", flag: "🇲🇱" },
    { id: "mt", value: "Malta", flag: "🇲🇹" },
    { id: "mh", value: "Marshall Islands", flag: "🇲🇭" },
    { id: "mr", value: "Mauritania", flag: "🇲🇷" },
    { id: "mu", value: "Mauritius", flag: "🇲🇺" },
    { id: "mx", value: "Mexico", flag: "🇲🇽" },
    { id: "fm", value: "Micronesia", flag: "🇫🇲" },
    { id: "md", value: "Moldova", flag: "🇲🇩" },
    { id: "mc", value: "Monaco", flag: "🇲🇨" },
    { id: "mn", value: "Mongolia", flag: "🇲🇳" },
    { id: "me", value: "Montenegro", flag: "🇲🇪" },
    { id: "ma", value: "Morocco", flag: "🇲🇦" },
    { id: "mz", value: "Mozambique", flag: "🇲🇿" },
    { id: "mm", value: "Myanmar", flag: "🇲🇲" },
    { id: "na", value: "Namibia", flag: "🇳🇦" },
    { id: "nr", value: "Nauru", flag: "🇳🇷" },
    { id: "np", value: "Nepal", flag: "🇳🇵" },
    { id: "nl", value: "Netherlands", flag: "🇳🇱" },
    { id: "nz", value: "New Zealand", flag: "🇳🇿" },
    { id: "ni", value: "Nicaragua", flag: "🇳🇮" },
    { id: "ne", value: "Niger", flag: "🇳🇪" },
    { id: "ng", value: "Nigeria", flag: "🇳🇬" },
    { id: "kp", value: "North Korea", flag: "🇰🇵" },
    { id: "mk", value: "North Macedonia", flag: "🇲🇰" },
    { id: "no", value: "Norway", flag: "🇳🇴" },
    { id: "om", value: "Oman", flag: "🇴🇲" },
    { id: "pk", value: "Pakistan", flag: "🇵🇰" },
    { id: "pw", value: "Palau", flag: "🇵🇼" },
    { id: "ps", value: "Palestine", flag: "🇵🇸" },
    { id: "pa", value: "Panama", flag: "🇵🇦" },
    { id: "pg", value: "Papua New Guinea", flag: "🇵🇬" },
    { id: "py", value: "Paraguay", flag: "🇵🇾" },
    { id: "pe", value: "Peru", flag: "🇵🇪" },
    { id: "ph", value: "Philippines", flag: "🇵🇭" },
    { id: "pl", value: "Poland", flag: "🇵🇱" },
    { id: "pt", value: "Portugal", flag: "🇵🇹" },
    { id: "pr", value: "Puerto Rico", flag: "🇵🇷" },
    { id: "qa", value: "Qatar", flag: "🇶🇦" },
    { id: "cg", value: "Republic of the Congo", flag: "🇨🇬" },
    { id: "ro", value: "Romania", flag: "🇷🇴" },
    { id: "ru", value: "Russia", flag: "🇷🇺" },
    { id: "rw", value: "Rwanda", flag: "🇷🇼" },
    { id: "kn", value: "Saint Kitts and Nevis", flag: "🇰🇳" },
    { id: "lc", value: "Saint Lucia", flag: "🇱🇨" },
    { id: "vc", value: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
    { id: "ws", value: "Samoa", flag: "🇼🇸" },
    { id: "sm", value: "San Marino", flag: "🇸🇲" },
    { id: "st", value: "São Tomé and Príncipe", flag: "🇸🇹" },
    { id: "sa", value: "Saudi Arabia", flag: "🇸🇦" },
    { id: "sn", value: "Senegal", flag: "🇸🇳" },
    { id: "rs", value: "Serbia", flag: "🇷🇸" },
    { id: "sc", value: "Seychelles", flag: "🇸🇨" },
    { id: "sl", value: "Sierra Leone", flag: "🇸🇱" },
    { id: "sg", value: "Singapore", flag: "🇸🇬" },
    { id: "sk", value: "Slovakia", flag: "🇸🇰" },
    { id: "si", value: "Slovenia", flag: "🇸🇮" },
    { id: "sb", value: "Solomon Islands", flag: "🇸🇧" },
    { id: "so", value: "Somalia", flag: "🇸🇴" },
    { id: "za", value: "South Africa", flag: "🇿🇦" },
    { id: "kr", value: "South Korea", flag: "🇰🇷" },
    { id: "ss", value: "South Sudan", flag: "🇸🇸" },
    { id: "es", value: "Spain", flag: "🇪🇸" },
    { id: "lk", value: "Sri Lanka", flag: "🇱🇰" },
    { id: "sd", value: "Sudan", flag: "🇸🇩" },
    { id: "sr", value: "Suriname", flag: "🇸🇷" },
    { id: "se", value: "Sweden", flag: "🇸🇪" },
    { id: "ch", value: "Switzerland", flag: "🇨🇭" },
    { id: "sy", value: "Syria", flag: "🇸🇾" },
    { id: "tw", value: "Taiwan", flag: "🇹🇼" },
    { id: "tj", value: "Tajikistan", flag: "🇹🇯" },
    { id: "tz", value: "Tanzania", flag: "🇹🇿" },
    { id: "th", value: "Thailand", flag: "🇹🇭" },
    { id: "tl", value: "Timor-Leste", flag: "🇹🇱" },
    { id: "tg", value: "Togo", flag: "🇹🇬" },
    { id: "to", value: "Tonga", flag: "🇹🇴" },
    { id: "tt", value: "Trinidad and Tobago", flag: "🇹🇹" },
    { id: "tn", value: "Tunisia", flag: "🇹🇳" },
    { id: "tr", value: "Turkey", flag: "🇹🇷" },
    { id: "tm", value: "Turkmenistan", flag: "🇹🇲" },
    { id: "tv", value: "Tuvalu", flag: "🇹🇻" },
    { id: "ug", value: "Uganda", flag: "🇺🇬" },
    { id: "ua", value: "Ukraine", flag: "🇺🇦" },
    { id: "ae", value: "United Arab Emirates", flag: "🇦🇪" },
    { id: "gb", value: "United Kingdom", flag: "🇬🇧" },
    { id: "us", value: "United States", flag: "🇺🇸" },
    { id: "uy", value: "Uruguay", flag: "🇺🇾" },
    { id: "uz", value: "Uzbekistan", flag: "🇺🇿" },
    { id: "vu", value: "Vanuatu", flag: "🇻🇺" },
    { id: "va", value: "Vatican City", flag: "🇻🇦" },
    { id: "ve", value: "Venezuela", flag: "🇻🇪" },
    { id: "vn", value: "Vietnam", flag: "🇻🇳" },
    { id: "ye", value: "Yemen", flag: "🇾🇪" },
    { id: "zm", value: "Zambia", flag: "🇿🇲" },
    { id: "zw", value: "Zimbabwe", flag: "🇿🇼" },
  ];
  return (
    <select
      className="bg-[#F7F9FB] py-2 border-[#EAEBEC] border-2 outline-none max-w-96 font-medium text-[#4D556F] text-sm"
      defaultValue=""
    >
      <option value="" disabled>
        Country Name
      </option>
      {countries.map((country) => (
        <option key={country.id} value={country.value}>
          {country.flag} {country.value}
        </option>
      ))}
    </select>
  );
}

export default Select;
